FROM golang:alpine

RUN mkdir $HOME/mailerservicelogs
WORKDIR $GOPATH/src/mailer-go/


# Copy everything from the current directory to the PWD(Present Working Directory) inside the container
COPY . .

RUN apk update && apk add git && go get github.com/scorredoira/email && go get github.com/lib/pq


ADD mail-cron /mail-cron

COPY startcron.sh /startcron.sh
RUN chmod 755 /startcron.sh
RUN /usr/bin/crontab /mail-cron

CMD ["/startcron.sh"]
